module.exports = [
    {id: "snow-like-a-canyon", name: "The Snow like a canyon", nameGeo: "თოვლი მზგავსად კანიონისა", url:"https://iili.io/HXMCvbp.md.jpg" },
    {id: "mountain-as-clouds-barrier", name: "The Mountain as clouds barrier",  nameGeo: "მთა როგორც ღრუბლების ბარიერი", url:"https://iili.io/HXMCzOl.md.jpg" },
    {id: "algae?", name: "A Algae?", nameGeo: "წყალმცენარე?", url: "https://iili.io/HXMFfI9.md.jpg" },
    {id: "puppy", name: "A Puppy", nameGeo: "ლეკვი", url: "https://iili.io/HXMrEyN.jpg" },
    {id: "spider-and-yellow-flower", name: "A Spider and a yellow flower", nameGeo: "ობობა და ყვითელი ყვავილი", url: "https://iili.io/HXMrRZF.jpg" },
    {id: "cockroach1", name: "A cockroach", nameGeo: "ხოჭო", url: "https://iili.io/HXMruTP.jpg" },
    {id: "black-spider", name: "A black spider", nameGeo: "შავი ობობა", url: "https://iili.io/HXMro3x.jpg" },
    {id: "ragweed", name: "A ragweed", nameGeo: "ამბროზია", url: "https://iili.io/HXMrJv2.jpg" },
    {id: "moonrise", name: "Moonrise", nameGeo: "მთვარის ამოსვლა", url: "https://iili.io/HXMrHYl.md.jpg" },
    {id: "hornet", name: "A hornet", nameGeo: "ბილაინის ბზიკი", url: "https://iili.io/HXMgp4f.md.jpg" },
    {id: "flower1", name: "An orange flower", nameGeo: "ნარინჯისფერი ყვავილი", url: "https://iili.io/HXMgtQn.md.jpg" },
    {id: "view1", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMg8Lg.md.jpg" },
    {id: "flying-ladybug", name: "A flying ladybug", nameGeo: "მფრინავი ჭიამაია", url: "https://iili.io/HXMU2cl.jpg" },
    {id: "flower2", name: "Flowers", nameGeo: "ყვავილები", url: "https://iili.io/HXMSmtn.md.jpg" },
    {id: "hedgehog", name: "A hedgehog", nameGeo: "ზღარბი", url: "https://iili.io/HXMShCb.jpg" },
    {id: "dill", name: "A Dill", nameGeo: "კამა", url: "https://iili.io/HXM8a5P.jpg" },
    {id: "red-crocus", name: "A Red crocus", nameGeo: "წითელი ზაფრანა", url: "https://iili.io/HXMvWH7.md.jpg" },
    {id: "blue-convolvulus-tricolor", name: "A blue convolvulus tricolor", nameGeo: "ლურჯი დილის ვარდი", url: "https://iili.io/HXMkw4p.jpg" },
    {id: "mushrooms", name: "Mushrooms", nameGeo: "სოკოები", url: "https://iili.io/HXMk0YP.md.jpg" },
    {id: "cockroach2", name: "A cockroach", nameGeo: "ხოჭო", url: "https://iili.io/HXMkxY7.md.jpg" },
    {id: "a-spider-and-a-rose", name: "A spider and a rose", nameGeo: "ობობა და ვარდი", url: "https://iili.io/HXMwies.jpg" },
    {id: "caterpillar1", name: "Caterpillar", nameGeo: "მატლი", url: "https://iili.io/HXMeikF.md.jpg" },
    {id: "view2", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMeg1V.md.jpg" },
    {id: "flower3", name: "A flower", nameGeo: "ყვავილი", url: "https://iili.io/HXMwTs2.md.jpg" },
    {id: "view3", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMh6GI.jpg" },
    {id: "eryngium", name: "A Eryngium", nameGeo: "სეტერო ეკალი", url: "https://freeimage.host/i/20210702-200315.HXMhw41" },
    {id: "onion", name: "A onion", nameGeo: "ხახვი", url: "https://iili.io/HXMho2n.md.jpg" },
    {id: "small-tettigonioidea ", name: "A small tettigonioidea ", nameGeo: "პატარა კუტკალია", url: "https://iili.io/HXMh3IR.md.jpg" },
    {id: "cockroach2", name: "A cockroach", nameGeo: "ხოჭო", url: "https://iili.io/HXMXrge.jpg" },
    {id: "view3", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMXAf1.jpg" },
    {id: "snail", name: "A snail", nameGeo: "ლოკოკინა", url: "https://iili.io/HXMXoDQ.jpg" },
    {id: "flower4", name: "A flower 4", nameGeo: "ყვავილი 4", url: "https://iili.io/HXMWNoB.md.jpg" },
    {id: "flower5", name: "A flower 5", nameGeo: "ყვავილი 5", url: "https://iili.io/HXMWGcu.md.jpg" },
    {id: "view4", name: "A view 4", nameGeo: "ხედი 4", url: "https://iili.io/HXMWIFn.md.jpg" },
    {id: "rumex-pulcher", name: "Rumex pulcher", nameGeo: "რომელიღაც მცენარე", url: "https://iili.io/HXMVQvj.md.jpg" },
    {id: "white-convolvulus-tricolor", name: "A white convolvulus tricolor", nameGeo: "თეთრი დილის ვარდი", url: "https://iili.io/HXMV6G9.md.jpg" },
    {id: "flower6", name: "A flower 6", nameGeo: "ყვავილი 6", url: "https://iili.io/HXMVAhB.md.jpg" },
    {id: "flower7", name: "A flower 7", nameGeo: "ყვავილი 7", url: "https://iili.io/HXMVvp4.jpg" },
    {id: "flower7", name: "A flower 7", nameGeo: "ყვავილი 7", url: "https://iili.io/HXMVdml.jpg" },
    {id: "flower8", name: "A flower 8", nameGeo: "ყვავილი 8", url: "https://iili.io/HXMVJe4.jpg" },
    {id: "flower9", name: "A flower 9", nameGeo: "ყვავილი 9", url: "https://iili.io/HXMVH7f.md.jpg" },
    {id: "ladybug", name: "A ladybug", nameGeo: "ჭიამაია", url: "https://iili.io/HXMMaR4.md.jpg" },
]

