module.exports = [
    {id: "snow-like-a-canyon", name: "The Snow like a canyon", nameGeo: "თოვლი მზგავსად კანიონისა", url:"https://iili.io/HXMCvbp.md.jpg" },
    {id: "mountain-as-clouds-barrier", name: "The Mountain as clouds barrier",  nameGeo: "მთა როგორც ღრუბლების ბარიერი", url:"https://iili.io/HXMCzOl.md.jpg" },
    {id: "algae?", name: "A Algae?", nameGeo: "წყალმცენარე?", url: "https://iili.io/HXMFfI9.md.jpg" },
    {id: "puppy", name: "A Puppy", nameGeo: "ლეკვი", url: "https://iili.io/HXMrEyN.jpg" },
    {id: "spider-and-yellow-flower", name: "A Spider and a yellow flower", nameGeo: "ობობა და ყვითელი ყვავილი", url: "https://iili.io/HXMrRZF.jpg" },
    {id: "cockroach1", name: "A cockroach", nameGeo: "ხოჭო", url: "https://iili.io/HXMruTP.jpg" },
    {id: "black-spider", name: "A black spider", nameGeo: "შავი ობობა", url: "https://iili.io/HXMro3x.jpg" },
    {id: "ragweed", name: "A ragweed", nameGeo: "ამბროზია", url: "https://iili.io/HXMrJv2.jpg" },
    {id: "moonrise", name: "Moonrise", nameGeo: "მთვარის ამოსვლა", url: "https://iili.io/HXMrHYl.md.jpg" },
    {id: "hornet", name: "A hornet", nameGeo: "ბილაინის ბზიკი", url: "https://iili.io/HXMgp4f.md.jpg" },
    {id: "flower1", name: "An orange flower", nameGeo: "ნარინჯისფერი ყვავილი", url: "https://iili.io/HXMgtQn.md.jpg" },
    {id: "view1", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMg8Lg.md.jpg" },
    {id: "flying-ladybug", name: "A flying ladybug", nameGeo: "მფრინავი ჭიამაია", url: "https://iili.io/HXMU2cl.jpg" },
    {id: "flower2", name: "Flowers", nameGeo: "ყვავილები", url: "https://iili.io/HXMSmtn.md.jpg" },
    {id: "hedgehog", name: "A hedgehog", nameGeo: "ზღარბი", url: "https://iili.io/HXMShCb.jpg" },
    {id: "dill", name: "A Dill", nameGeo: "კამა", url: "https://iili.io/HXM8a5P.jpg" },
    {id: "red-crocus", name: "A Red crocus", nameGeo: "წითელი ზაფრანა", url: "https://iili.io/HXMvWH7.md.jpg" },
    {id: "blue-convolvulus-tricolor", name: "A blue convolvulus tricolor", nameGeo: "ლურჯი დილის ვარდი", url: "https://iili.io/HXMkw4p.jpg" },
    {id: "mushrooms", name: "Mushrooms", nameGeo: "სოკოები", url: "https://iili.io/HXMk0YP.md.jpg" },
    {id: "cockroach2", name: "A cockroach", nameGeo: "ხოჭო", url: "https://iili.io/HXMkxY7.md.jpg" },
    {id: "caterpillar1", name: "Caterpillar", nameGeo: "მატლი", url: "https://iili.io/HXMeikF.md.jpg" },
    {id: "view2", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMeg1V.md.jpg" },
    {id: "a-spider-and-a-rose", name: "A spider and a rose", nameGeo: "ობობა და ვარდი", url: "https://iili.io/HXMwies.jpg" },
]

